#!/bin/bash

#set folder for file-change-rss
FOLDERFILECHANGERSS="/home/pi/file-change-rss"


###script###
INOTIFY="$FOLDERFILECHANGERSS/inotify"

mkdir $FOLDERFILECHANGERSS

#curl -L  https://github.com/PowerShell/PowerShell/releases/download/v7.1.3/powershell-7.1.3-linux-x64.tar.gz -o /tmp/powershell.tar.gz
#curl file-change-RSS.ps1 -o $FOLDERFILECHANGERSS/file-change-RSS.ps1
#curl inotify -o $INOTIFY
#chmod +x INOTIFY

crontab -l > $FOLDERFILECHANGERSS/cronjobs
echo '@reboot sleep 60 && screen -dmS filechangerss && screen -S filechangerss -X stuff "'$INOTIFY'^M"' >> $FOLDERFILECHANGERSS/cronjobs
echo "*/5 * * * * pwsh $FOLDERFILECHANGERSS/file-change-RSS.ps1" >> $FOLDERFILECHANGERSS/cronjobs
crontab $FOLDERFILECHANGERSS/cronjobs
rm $FOLDERFILECHANGERSS/cronjobs
screen -dmS filechangerss && screen -S filechangerss -X stuff "'$INOTIFY'^M"